GET http://127.0.0.1:3001/user/getUsers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJDYW1taSIsImVtYWlsIjoiY21oMkBtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDdaUzZXRnZLYkVMZ0lkYWZTVjFMWi53VDQvRXlPcWt6L0c0WUo3WlBNalVWQlFxaENYOWJlIiwiaWF0IjoxNzQ0MjAzNTc1LCJleHAiOjE3NDQyMDcxNzV9.Rdr-20Y3FrpQWmsvRGVmKib9FDsH_jBOicm1_uwTYNg
###

GET http://127.0.0.1:3001/setup/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJDYW1taSIsImVtYWlsIjoiY21oMkBtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDdaUzZXRnZLYkVMZ0lkYWZTVjFMWi53VDQvRXlPcWt6L0c0WUo3WlBNalVWQlFxaENYOWJlIiwiaWF0IjoxNzQ0MjA1MDMxLCJleHAiOjE3NDQyMDg2MzF9.PXIlALNjoao2FZWcWRwV8uewj7d67VtbfcSizASGcqw
###

POST http://127.0.0.1:3001/user/createUser
Content-Type: application/json

{
    "name": "Cammi",
    "email": "cmh2@mail.com",
    "password": "123456"

}

###

POST http://127.0.0.1:3001/auth/login
Content-Type: application/json

{
    "email": "cmh2@mail.com",
    "password": "123456"
}