GET http://127.0.0.1:3001/setup/getExpenses/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJDYW1taSIsImVtYWlsIjoiY21oMkBtYWlsLmNvbSIsImlhdCI6MTc0NTIzODQwMSwiZXhwIjoxNzQ1MjQyMDAxfQ.CLgGCDNKqQkuLjGxUnaeJKkh4YaTT3_INOkbMDxCgxA
###

GET http://127.0.0.1:3001/setup/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJDYW1taSIsImVtYWlsIjoiY21oMkBtYWlsLmNvbSIsImlhdCI6MTc0NTIzODQwMSwiZXhwIjoxNzQ1MjQyMDAxfQ.CLgGCDNKqQkuLjGxUnaeJKkh4YaTT3_INOkbMDxCgxA
###

POST http://127.0.0.1:3001/user/createUser
Content-Type: application/json

{
    "name": "Cammi",
    "email": "cmh2@mail.com",
    "password": "123456"

}

###

POST http://127.0.0.1:3001/auth/login
Content-Type: application/json

{
    "email": "cmh2@mail.com",
    "password": "123456"
}
###
POST http://127.0.0.1:3001/setup/postExpense
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJDYW1taSIsImVtYWlsIjoiY21oMkBtYWlsLmNvbSIsImlhdCI6MTc0NTA3MDU0NiwiZXhwIjoxNzQ1MDc0MTQ2fQ.R4jBk0c4neJHbi0mT0VClyAQQyJG_MT2ERbnUCrw4bY
Content-Type: application/json

{
    "name": "testname",
    "amount": 123,
    "payRate": 3,
    "categoryID": 1
}